config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'

  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
	validates :description,  presence: true, length: { maximum: 50 }
	validates :deadline,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :all_tasks, only: [:index, :create, :update, :destroy]
  before_action :set_tasks, only: [:edit, :update, :destroy]


  def new
    @task = Task.new
  end

  def create
    #@task = Task.create(task_params)

    @task = Task.new(task_params)
    if @task.save
      flash[:success] = "Task Create"
    else
      render 'new'
    end

  end



  def update
    #puts task_params
    #@task.update_attributes(task_params)

    if @task.update_attributes(task_params)
      flash[:success] = "Task updated"
    else
      render 'edit'
    end

  end




  def destroy
    @d_id = @task.id
    p "d_id is #{@d_id} ======================"
    @task.destroy
  end

  private

    def all_tasks
      @tasks = Task.all
    end

    def set_tasks
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:description, :deadline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

	<div class="col-md-5 col-md-offset-1">
	  <h2>HOYEE Task List</h2>
	</div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>AjaxTask</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
  <body>
    <div class="container-fluid">
      <div class="row" id="header"><%= render 'layouts/header' %></div>
      <div class="row content"><%= yield %></div>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@task.errors.count, "error") %>.
    </div>
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/_form.html.erb

<%= form_for @task, remote: true do |f|   %>
  
  <%= render 'shared/error_messages' %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control"%>
  <br>
  <%= f.label :deadline %>
  <%= f.text_field :deadline , id:'datetimepicker1', :value =>@task.deadline,  class: "form-control" %>
  <br>
  <%= f.submit  class: "btn btn-default" %>
  <%= link_to "Cancle", "#" , class: "btn btn-primary", id:"cancle" %>

<% end %>


app/views/tasks/_task.html.erb
<li class="list-group-item list-group-item-info"  id="task-lili-<%= task.id %>">
  <!--<%= task.description %>

  <span class="deadline"><%= task.deadline %> </span>  -->


  <span class="has-tooltip" data-toggle="tooltip" title="<%= "Please Get It Done by #{task.deadline.strftime("%B %d, %Y %H:%M:%S")}" %>">
    <%= task.description.split("\n").first %> ......
  </span>


  <span class="edit">
    

    <!-- Button trigger modal -->
    <button class="btn btn-primary btn-xs" data-toggle="modal" data-target="#task-<%= task.id %>-descriptions">
      Show
    </button>
      <!-- Modal -->
      <div class="modal fade" id="task-<%= task.id %>-descriptions" tabindex="-1" role="dialog" aria-labelledby="task-<%= task.id %>-label" >
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="task-<%= task.id %>-label">Task</h4>
            </div>
            <div class="modal-body">
              <%= simple_format(task.description) %>
            </div>


            <div class="modal-body">
              <%= "Due on #{task.deadline.strftime("%B %d, %Y %H:%M:%S")}"   %>
            </div>


            <div class="modal-footer">
              <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>


    <%= link_to edit_task_path(task), remote: true do %>
      <button class="btn btn-primary btn-xs">Edit</button>
    <% end %>

    
    <%= link_to task, remote: true, method: :delete,
        data: { confirm: 'Are you sure?' } do %>
      <button class="btn btn-danger btn-xs">Delete!</button>
    <% end %>

  </span>


</li>


<%= render(:partial => 'tasksdisplay', :formats => ["js.erb"]) %>

app/views/tasks/_tasksdisplay.js.erb
<script>
	$(document).ready(function() {
		$('.has-tooltip').tooltip();
	});
</script>

app/views/tasks/create.js.erb
$('#tasks').html("<%= escape_javascript(render @tasks) %>");
$('#task-form').slideUp(350);

app/views/tasks/destroy.js.erb
//$('#tasks').html("<%= escape_javascript(render @tasks) %>");
$('#task-lili-<%= @d_id %>').fadeOut(800, function(){ $(this).remove();});


app/views/tasks/edit.js.erb
$('#task-form').html("<%= escape_javascript(render 'form') %>");
$('#task-form').slideDown(350);

<%= render 'datetimepicker' %>

app/views/tasks/index.html.erb
<div class="row" style="border: 0px solid;">
  <div class="col-md-2 col-md-offset-1" style="border: 0px  solid;">
    <h2>Tasks</h2>
  </div>

  <div class="col-md-2 col-md-offset-4" style="border: 0px   solid;">



    <%= link_to new_task_path, class: 'btn btn-success', remote: true do %>
      <i class="glyphicon glyphicon-plus"></i> New Task
    <% end %>


  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-1" id="task-form" style="display:none;"></div>
</div>

<div class="row">
  <div class="col-md-7 col-md-offset-1" id="tasks"><%= render @tasks %></div>
</div>

app/views/tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

<%= render 'datetimepicker' %>


app/views/tasks/update.js.erb
$('#tasks').html("<%= escape_javascript(render @tasks) %>");
$('#task-form').slideUp(350);